version: '3'
services:
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5005:5000
    volumes:
      - ./server:/server
    command: npm run server
  client:
    build: ./client
    expose:
      - 3000
      - 35729
    ports:
      - 3003:3000
      - 35729:35729
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    command: npm run start